### PR TITLE
new tutorial 'Introduction to write Smart Contracts in Rust and Ink!

### PR DESCRIPTION
**Pull request by GuiGou12358**
Add a new tutorial `Introduction to write Smart Contracts in Rust and Ink!`

### CODE REVIEW

**Review by meganskye — CHANGES_REQUESTED** [review]
you should ensure any errors thrown during a test build are cleared up before submitting a PR.

file and folder names shouldn't contain characters that need to be escaped. for prettier styling of docusaurus document and section titles, use:

```
---
title: Pretty Name
---
```
and/or `_category_.json` files.

**Comment by GuiGou12358** [comment]
@meganskye The file has been renamed and the build is fine now.

**Review by Gunit2481 — APPROVED** [review]
LGTM

**Review by meganskye — APPROVED** [review]
lgtm

**Review by GuiGou12358 — COMMENTED** [review]
Agree with the changes done by @Gunit2481

**Pull request merged**
